require("zach.cmp")
require("zach.lsp")
require("zach.telescope")
require("zach.treesitter")
-- require("zach.nvim-tree")
require("zach.autopairs")
require("zach.gitsigns")
require("zach.comments")
require("zach.options")
require("zach.packer")
require("zach.keymap")
require("zach.set")
